bugfix: fixed filled spot in some elder sprites
Thlumyn/clangen pull request #186
Opened 2022-10-12 14:20 UTC by Ryos00

2022-10-14 13:07 UTC, sedgestripe approved these changes

2022-10-14 16:10 UTC, Lixxis requested changes
Is it normal, that white single colors have outlines?
![image](https://user-images.githubusercontent.com/110975120/195892310-a0a73416-ad32-4a96-9cea-9a5c2e7cce4d.png)

2022-10-14 16:56 UTC, Ryos00 commented
> Is it normal, that white single colors have outlines? ![image](https://user-images.githubusercontent.com/110975120/195892310-a0a73416-ad32-4a96-9cea-9a5c2e7cce4d.png)

Yes, that's how the old ones were too :)

2022-10-14 22:04 UTC, Lixxis approved these changes

2022-10-18 01:31 UTC, Thlumyn approved these changes

2022-10-18 01:31 UTC, merged