other/bugfixes: commented out unfinished features & fixed wars
Thlumyn/clangen pull request #216
Opened 2022-10-25 17:28 UTC by Ryos00

- commented out exile
- commented out map
- commented out Cats Outside The Clan
- removed numpy and noise from requirements
- fixed wars and clan relations junk

2022-10-25 17:29 UTC, Ryos00 commented
pretend u don't see all those commits of me failing to fix relations

2022-10-25 17:45 UTC, sedgestripe approved these changes

2022-10-25 19:07 UTC, Lixxis requested changes

2022-10-25 19:07 UTC, Lixxis commented on scripts/events.py
> +                    other_clan.relations = other_clan.relations
This line is irreleavant

2022-10-25 19:07 UTC, Lixxis commented on scripts/events.py
> +            print(other_clan.relations)
Maybe if it is not needed anymore, you could delete this line

2022-10-25 20:15 UTC, Lixxis approved these changes

2022-11-18 17:04 UTC, Dpeta commented on scripts/patrol.py
> +        if randint(1, 1) == 1 and self.other_clan is not None:
```suggestion
        if self.other_clan is not None:
```

2022-11-18 17:06 UTC, Dpeta commented on scripts/patrol.py
> +        if randint(1, 1) == 1 and self.other_clan is not None:
(Not a full review btw, just noticed that xd)

2022-11-18 17:59 UTC, Thlumyn approved these changes

2022-11-18 18:00 UTC, merged